# Generated by Django 4.1.2 on 2024-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
